version: '2'
services:

  sqs:
    image: roribio16/alpine-sqs
    container_name: sqs
    ports:
      - 9324:9324
      - 9325:9325

  database:
    image: "postgres"
    env_file:
      - localDb.env
    ports:
      - 5432:5432

  test-database:
    image: "postgres"
    env_file:
      - localDbTest.env
    ports:
      - 5433:5432

